-- users
CREATE TABLE IF NOT EXISTS users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_code VARCHAR(20) NOT NULL,
  emp_no VARCHAR(32),
  name VARCHAR(50),
  phone VARCHAR(30),
  email VARCHAR(120) UNIQUE,
  password_hash VARCHAR(200) NOT NULL,
  role ENUM('super_admin','admin','user') NOT NULL DEFAULT 'user',
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS refresh_tokens(
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  token_hash VARCHAR(200) NOT NULL,
  expires_at DATETIME NOT NULL,
  revoked_at DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sensors(
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_code VARCHAR(20) NOT NULL,
  place_type ENUM('SE','AR') NOT NULL,
  place_code VARCHAR(30) NOT NULL,
  priority INT DEFAULT 0,
  name VARCHAR(100) NOT NULL,
  enabled TINYINT(1) DEFAULT 1,
  alarm_enabled TINYINT(1) DEFAULT 1,
  img VARCHAR(255), x INT DEFAULT 0, y INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_logs(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_code VARCHAR(20), user_id INT,
  action VARCHAR(40), description VARCHAR(500),
  ip VARCHAR(64), ts DATETIME
);
